---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
  - set_fact:
      main_dir: "{{ playbook_dir }}"
      dist_dir: "{{ playbook_dir }}/dist"
  - name: Init raspi machine
    docker_container:
      name: raspi
      image: ptrsr/pi-ci
      command: init
      volumes:
        - "{{ dist_dir|default(omit) }}:/dist"
      auto_remove: yes
      interactive: yes
      tty: yes
      detach: no
  # - name: Resize raspi machine
  #   docker_container:
  #     name: raspi
  #     image: ptrsr/pi-ci
  #     command: resize 12G -y
  #     volumes:
  #       - "{{ dist_dir|default(omit) }}:/dist"
  #     auto_remove: yes
  #     interactive: yes
  #     tty: yes
  #     detach: no
  # - name: Start raspi machine
  #   docker_container:
  #     name: raspi
  #     image: ptrsr/pi-ci
  #     command: start
  #     state: started
  #     tls_hostname: localhost
  #     published_ports:
  #       - 2222:2222
  #     volumes:
  #       - "{{ dist_dir|default(omit) }}:/dist"

- hosts: raspi
  gather_facts: no
  tasks:
  - name: Wait for machine startup
    wait_for_connection:
      timeout: 300
# . "$HOME/.cargo/env"
# cargo install --git https://github.com/Spotifyd/spotifyd.git

# alsaloop -r 48000 -C default:CARD=Device -P default:CARD=audioinjectorpi -l 1024 -U