---
- name: Configure OverlayFS on Raspi
  hosts: raspi
  become: yes
  tasks:

    - name: Create directory for initramfs script
      file:
        path: /etc/initramfs-tools/scripts/init-top
        state: directory
        mode: '0755'

    - name: Upload the initramfs overlayfs setup script
      copy:
        dest: /etc/initramfs-tools/scripts/init-top/overlayfs_setup
        content: |
          #!/bin/sh

          # Mount the FAT32 partition
          mount -t vfat /dev/sda1 /mnt

          # Read the file containing the list of SquashFS images
          lower_dirs=""
          while IFS= read -r squashfs_image; do
              # Mount each SquashFS image as a loopback device
              mkdir -p /mnt/loopdir_$(basename "$squashfs_image")
              mount -o loop,ro -t squashfs "/mnt/$squashfs_image" "/mnt/loopdir_$(basename "$squashfs_image")"

              # Add the mounted directory to the list of lower directories
              if [ -z "$lower_dirs" ]; then
                  lower_dirs="/mnt/loopdir_$(basename "$squashfs_image")"
              else
                  lower_dirs="$lower_dirs:/mnt/loopdir_$(basename "$squashfs_image")"
              fi
          done < /mnt/squashfs_list.txt

          # Check for an attached disk to use as the upper directory
          if ls /dev/sd[b-z]1 >/dev/null 2>&1; then
              upper_device=$(ls /dev/sd[b-z]1 | head -n 1)
              echo "Using $upper_device as the upper directory"
              mkdir -p /mnt/upperdisk
              mount $upper_device /mnt/upperdisk
              upper_dir="/mnt/upperdisk"
          else
              echo "No attached disk found, using tmpfs as the upper directory"
              mkdir -p /mnt/upperdir
              mount -t tmpfs tmpfs /mnt/upperdir
              upper_dir="/mnt/upperdir"
          fi

          # Create a work directory for OverlayFS
          mkdir -p /mnt/workdir

          # Mount the overlay filesystem
          mkdir -p /mnt/root
          mount -t overlay overlay -o lowerdir=$lower_dirs,upperdir=$upper_dir,workdir=/mnt/workdir /mnt/root

          # Change root to the new overlay root
          exec switch_root /mnt/root /sbin/init
        mode: '0755'

    - name: Update initramfs on Raspi
      command: update-initramfs -u
      args:
        warn: false

    - name: Reboot the system to apply changes
      reboot:
        msg: "Rebooting to apply new initramfs configuration"
        connect_timeout: 5
        reboot_timeout: 300
